# Generated by Django 6.1.1 on 2026-09-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0002_remove_contact_id_remove_experience_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_serial_number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(max_length=200),
        ),
    ]
