# Generated by Django 6.1.1 on 2026-09-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0003_projects_project_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
    ]
