# Generated by Django 6.1.1 on 2026-09-08 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0004_contact_id_alter_contact_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='projects/projects_image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='portfolio_website.projects')),
            ],
        ),
    ]
