# Generated by Django 6.1.1 on 2026-09-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0005_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=models.CharField(max_length=500),
        ),
    ]
