# Generated by Django 6.1.1 on 2026-09-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0006_alter_projects_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_long_description',
            field=models.TextField(default='Long description will be provided very soon'),
            preserve_default=False,
        ),
    ]
