# Generated by Django 6.1.1 on 2026-09-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0007_projects_project_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_focus',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_status',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
