# Generated by Django 6.1.1 on 2026-09-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0008_projects_project_focus_projects_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
