# Generated by Django 6.1.1 on 2026-09-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0009_projects_project_github_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='testemonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
