# Generated by Django 6.1.1 on 2026-09-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0011_contact_created_at_contact_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='blockvisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=250)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
