# Generated by Django 6.1.1 on 2026-09-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0012_blockvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockvisitor',
            name='duration',
            field=models.DurationField(auto_created=True),
        ),
    ]
