# Generated by Django 6.1.1 on 2026-09-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0013_alter_blockvisitor_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockvisitor',
            name='duration',
        ),
    ]
